/**
 * @author Maike
 */
@isTest(seeAllData = true)
public class ProjectFilterTest {
   /* 
    @isTest
    static void filterByEnterpriseProjectStartedTest() {

        List<Project__c> projects = new List<Project__c>{
                new Project__c(ProjectName__c = 'TopiRun2022')
               ,new Project__c(ProjectName__c = 'TopiRun2022 Segundo Semestre') 
        };

    ProjectFilter filter = new ProjectFilter();

    List<Project__c> filteredProjects = filter.filterByEnterpriseProjectStarted(projects, filteredProjects );

    System.assertEquals(!filteredProjects.isEmpty());

    }*/
    
}
